#!/bin/bash
# More5Stars Quick Start

echo "🌟 More5Stars — Review Routing SaaS"
echo ""
echo "Local test environment:"
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Start the server:"
echo "   npm start"
echo ""
echo "3. Open in browser:"
echo "   http://localhost:3000"
echo ""
echo "4. Admin dashboard:"
echo "   http://localhost:3000/admin"
echo "   Login: admin@more5stars.net / changeme123"
echo ""
echo "5. Demo customer page:"
echo "   http://localhost:3000/r/demo"
echo ""
echo "---"
echo ""
echo "Production deployment:"
echo "   See DEPLOYMENT.md for Render/Railway/Fly instructions"
echo ""
echo "Selling to customers:"
echo "   See CUSTOMER_PITCH.md for sales materials"
echo ""
